name: 'Spectacular Documentation Generation Action'
description: 'Generates your documentation'
branding:
  icon: 'heart'
  color: 'red'
inputs:
  github-personal-access-token: 
    description: 'Your github personal access token'
    required: true
    default: 'xxxxxxx'
  style:
    description: 'Style for output of documentation'
    required: true
    default: 'Simple'
  files-input:
    description: 'File paths to generate for'
    required: true
    default: '["default value"]'
    type: array
    items:
      type: string
runs:
  using: 'node20'
  main: 'dist/index.js'
