name: 'Spectacular Documentation Generation Action'
description: 'Generates your documentation'
branding:
  icon: 'heart'
  color: 'red'
inputs:
  github-username:
    description: 'Your github username'
    required: true
    default: 'username'
  style:
    description: 'Style for output of documentation'
    required: true
    default: 'Simple'
  files-input:
    description: 'File paths to generate for'
    required: true
    default: '["default value"]'
    type: array
    items:
      type: string
outputs:
  generated-docs: 
    description: 'HTML for generated documents'
  htmlZip:
    description: 'Zip folder containing HTML files'
    path: 'output.zip
runs:
  using: 'node20'
  main: 'dist/index.js'
