name: 'Spectacular Documentation Generation Action'
description: 'Generates your documentation'
branding:
  icon: 'heart'
  color: 'red'
inputs:
  style:
    description: 'Style for output of documentation'
    required: true
    default: 1
  name-of-docs: 
    description: 'Titles of documentation'
    required: true
    default: []
    type: array
    items:
      type: string
  files-input:
    description: "File paths to generate for"
    required: true
    default: []
    type: array
    items:
      type: string
outputs:
  generated-docs: 
    description: 'HTML for generated documents'
    default: []
    type: array
    items:
      type: string
runs:
  using: 'node20'
  main: 'dist/index.js'
